[build]
rustflags = [
    "-Z", "location-detail=none",           # Remove file, line, and column information for panic!() to reduce binary size
    "-C", "link-arg=-s",                    # Strip all symbols from the final binary (linker flag)
    "-C", "link-arg=-Wl,--gc-sections",     # Remove unused sections from the binary (garbage collection)
    "-C", "link-arg=-Wl,--strip-all",       # Strip all symbols and relocation information
    "-C", "target-feature=+crt-static",     # Statically link the C runtime library instead of using dynamic linking
    "-C", "prefer-dynamic=false",           # Force static linking instead of dynamic linking (This is due to LTO requiring this option)
    "-C", "debuginfo=0",                    # Disable debug information generation completely
    "-C", "symbol-mangling-version=v0",     # Use legacy symbol mangling for smaller symbols
    "-Z", "share-generics=off",             # Disable sharing of generic instantiations across crates
    "-Z", "threads=1",                      # Use single-threaded compilation (may reduce memory usage)
    "-Z", "unstable-options"                # Enable unstable compiler options (required for -Z flags)
]
